name: Deploy Example Site

on:
  push:
    branches:
      - main # GitHub repository branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:         
      - name: Checkout repository and update Hugo themes
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Hugo site
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ghcr.io/ssmiller25/r15-papercss-hugo-theme
          push: never
          runCmd: |
            make build-example

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: r15-papercss-hugo-theme # Specify your project name
          branch: main # Specify the production branch for Cloudflare Pages
          directory: exampleSite/public