name: Prebuild AI workspace

on:
  push:
    branches:
      - main # GitHub repository branch
    paths:
      - '.devcontainer/**'
      - 'requirements.txt'
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:  
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
    - name: Login to ghcr
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Pre-build dev container image
      uses: devcontainers/ci@v0.3
      with:
        imageName: ghcr.io/ssmiller25/r15-papercss-hugo-theme
        cacheFrom: ghcr.io/ssmiller25/r15-papercss-hugo-theme
        push: always